### ISSUE TITLE
Return to dock problem

### ISSUE THREAD

**Issue by PeteRepeat77** [Whytey/moebot-hass-integration#35]
Seems that in the mower device page "return to dock" = pauses, cancels and returns to dock so nice change.

However when choosing return to dock in an automation doesn't work. And there is no pause or cancel in automation to make it return.

If i pause and cancel in the moebot app, then return to dock in a rule in home assistant works.

**Comment by PeteRepeat77** [comment]
Sorry seems this could be related to the other open issue. Itnwas in Spanish so wasn't obvious until now. I'll close this so it doesn't create a duplicate.

Issue is current with latest version

**Comment by PeteRepeat77** [comment]
Closed due to potential duplicate

**Comment by Whytey** [comment]
Hi,

Are you using the lawn mower or the vacuum component?

Recommend using lawn mower.

I just trialled this and it all worked for me. The nuance (nuisance?) is
that the lawn mower component only supports a small number of states so
when it is returning to the dock it indicates it is still mowing. It may be
worth watching the mower state sensor as you trial your automations?

I don't think this is related to the Spanish bug.

Cheers

**Comment by Whytey** [comment]
Hi @PeteRepeat77 

I am on my laptop now so can provide a better response.

From your automations, you should be calling one of the three lawn mower services available:
![image](https://github.com/user-attachments/assets/7a7078dc-86cc-45da-b32d-9d6816f38e21)

Don't forget to specify your lawn mower entity.

As I indicated above, when the mower is returning to the dock, it may appear like it is still mowing.  That is because it is how the PARK start is mapped in lawn mower.
![image](https://github.com/user-attachments/assets/5b497fc3-7449-4b77-a96b-44c383b9ad38)

I don't think this is a defect.  If you disagree, feel free to reopen and provide any logs that might help.

**Comment by PeteRepeat77** [comment]
Ahh that's the problem. I wasn't calling the service, I was treating it  as a vaccum device. Starting it as a vaccum works fine.

Changed it and it works now.

**Comment by Whytey** [comment]
Excellent. Still recommend the lawn mower device. I expect to remove vacuum
in any future release 😬

**Comment by PeteRepeat77** [comment]
Thanks. I've changed all start commands to the mower service.

As the zones are found under the device category I chose that start because, well it was there 😁

On a seperate note (unrelated) do you know if the rain sensor state is presented? Maybe as an "emergency" state? I could go pour water on the sensor and find out tomorrow instead of just asking = lazy

**Comment by Whytey** [comment]
I haven't seen any indication that rain state is reported. Unfortunately.
